# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build pdf-generator`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t pdf-generator`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system pdf-generator && \
          adduser --system -G pdf-generator pdf-generator

COPY dist/pdf-generator pdf-generator
RUN chown -R pdf-generator:pdf-generator .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix pdf-generator --omit=dev -f install

CMD [ "node", "pdf-generator" ]
